In [1]:
from sklearn.datasets import load_svmlight_file
from sklearn.model_selection import train_test_split

import numpy as np

In [2]:
from adaboost_exp import *

In [3]:
# Data path

"""three datasets: a9a, breast-cancer, gisette"""

data_dir = "/home/tati/Documents/data/"

a9 = data_dir + "a9/a9a.txt"
a9_test = data_dir + "a9/a9a.t"

breast = data_dir + "breast-cancer/breast-cancer.txt"

gisette = data_dir + "gisette/gisette_scale"
gisette_test = data_dir + "gisette/gisette_scale.t"

In [4]:
# Load breast-cancer dataset and split into train/test by 0.8/0.2
breast = load_svmlight_file(breast, n_features=10)
breast_X, breast_X_test, breast_y, breast_y_test = train_test_split(
    breast[0], breast[1], train_size=0.8, test_size=0.2)

In [5]:
clf = example_DV(breast_X, breast_y, breast_X_test, breast_y_test,
           dv_interval=100,
           n_estimators=100,
           dv_max_iter=200,
           dv_loss="log",
           dv_penalty="none")

[Iter 0] error=0.0714285714286
[Iter 1] error=0.0714285714286
[Iter 2] error=0.0457875457875
[Iter 3] error=0.0457875457875
[Iter 4] error=0.0384615384615
[Iter 5] error=0.032967032967
[Iter 6] error=0.0384615384615
[Iter 7] error=0.0347985347985
[Iter 8] error=0.032967032967
[Iter 9] error=0.0311355311355
[Iter 10] error=0.0384615384615
[Iter 11] error=0.025641025641
[Iter 12] error=0.0311355311355
[Iter 13] error=0.0311355311355
[Iter 14] error=0.0311355311355
[Iter 15] error=0.032967032967
[Iter 16] error=0.021978021978
[Iter 17] error=0.025641025641
[Iter 18] error=0.025641025641
[Iter 19] error=0.025641025641
[Iter 20] error=0.025641025641
[Iter 21] error=0.0238095238095
[Iter 22] error=0.0238095238095
[Iter 23] error=0.0238095238095
[Iter 24] error=0.021978021978
[Iter 25] error=0.0238095238095
[Iter 26] error=0.0238095238095
[Iter 27] error=0.021978021978
[Iter 28] error=0.021978021978
[Iter 29] error=0.021978021978
[Iter 30] error=0.0201465201465
[Iter 31] error=0.0201465201465

In [6]:
clf.estimator_weights_

array([ 0.78202188,  1.07185103,  1.22613221,  0.65261573,  0.5431024 ,
       -0.08829013,  0.34755345,  0.4951297 ,  0.43422192,  0.41010288,
       -0.2932333 ,  0.26452941,  0.2319877 ,  0.30456159,  0.32795046,
        0.25473877,  0.10983528,  0.42290123, -0.28040484,  0.23271282,
       -0.31302855,  0.22217885, -0.33673187,  0.19036251,  0.38897823,
        0.4078458 ,  0.2539559 ,  0.31259136, -0.23787338,  0.21277345,
       -0.31180781,  0.18642592, -0.35607712,  0.17118241, -0.36009282,
        0.12766243, -0.34484649,  0.19244998, -0.36012856,  0.19866847,
       -0.35942424,  0.16680567, -0.34614564,  0.16976236, -0.36532619,
        0.16068566, -0.36866236,  0.18207395,  0.29116797,  0.14436662,
       -0.32508878,  0.17697096, -0.36371818,  0.18704013, -0.02367221,
       -0.30298112,  0.17141973, -0.36826682,  0.17690355, -0.37288127,
        0.1489259 , -0.37846276,  0.15437204, -0.37809914,  0.17713796,
        0.10551228,  0.21891157, -0.39291992,  0.15138653, -0.38

In [7]:
clf = example_BINARY(breast_X, breast_y, breast_X, breast_y,
           n_estimators=50)

BINARY time=0.09848570823669434
	[Iter 0]: error=0.0714285714286
	[Iter 1]: error=0.0714285714286
	[Iter 2]: error=0.0457875457875
	[Iter 3]: error=0.0457875457875
	[Iter 4]: error=0.0384615384615
	[Iter 5]: error=0.032967032967
	[Iter 6]: error=0.0384615384615
	[Iter 7]: error=0.0347985347985
	[Iter 8]: error=0.032967032967
	[Iter 9]: error=0.0311355311355
	[Iter 10]: error=0.0384615384615
	[Iter 11]: error=0.025641025641
	[Iter 12]: error=0.0311355311355
	[Iter 13]: error=0.0311355311355
	[Iter 14]: error=0.0311355311355
	[Iter 15]: error=0.032967032967
	[Iter 16]: error=0.021978021978
	[Iter 17]: error=0.025641025641
	[Iter 18]: error=0.025641025641
	[Iter 19]: error=0.025641025641
	[Iter 20]: error=0.025641025641
	[Iter 21]: error=0.0238095238095
	[Iter 22]: error=0.0238095238095
	[Iter 23]: error=0.0238095238095
	[Iter 24]: error=0.021978021978
	[Iter 25]: error=0.0238095238095
	[Iter 26]: error=0.0238095238095
	[Iter 27]: error=0.021978021978
	[Iter 28]: error=0.021978021978
	[It

In [8]:
coef_init = np.array([clf.estimator_weights_])
coef_init.shape

(1, 50)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
vote_model = LogisticRegression(fit_intercept=False,
                                max_iter=100,
                                penalty='l2',
                                C=1,
                                warm_start=True)
X_map = np.array([est.predict(breast_X) for est in clf.estimators_]).T
vote_model.coef_ = coef_init
vote_model.fit(X_map, breast_y)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=True)

In [14]:
# clf.estimator_weights_ = vote_model.coef_[0]
(clf.predict(breast_X) != breast_y).sum() / len(breast_y)

0.018315018315018316

In [12]:
(vote_model.predict(X_map) != breast_y).sum() /  len(breast_y)

0.0054945054945054949

In [13]:
log_model = LogisticRegression(fit_intercept=True,
                                max_iter=20,
                                penalty='l1',
                                C=10)
log_model.fit(breast_X, breast_y)
print(log_model.n_iter_)
(log_model.predict(breast_X) != breast_y).sum() /  len(breast_y)


[17]


0.02197802197802198

In [22]:
(clf.estimators_[0].predict(breast_X)== clf.n_classes_).T.shape

(546,)

In [29]:
pred = sum((estimator.predict(breast_X) == clf.classes_[:, np.newaxis]).T * w for estimator, w in
zip(clf.estimators_, clf.estimator_weights_)) / clf.estimator_weights_.sum()

In [39]:
pred[:,0] *= -1

array([[-0.68984645,  0.31015355],
       [-0.71541758,  0.28458242],
       [-0.69744925,  0.30255075],
       ..., 
       [-0.71386424,  0.28613576],
       [-0.72645614,  0.27354386],
       [-0.39158118,  0.60841882]])

In [45]:
pred = pred.sum(axis=1)

In [48]:
clf.classes_.take(pred>0, axis=0)

array([ 2.,  2.,  2.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,
        2.,  4.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,  2.,  2.,  4.,  2.,
        2.,  2.,  2.,  4.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  4.,
        4.,  2.,  2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  4.,  2.,
        2.,  2.,  4.,  2.,  2.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,
        2.,  2.,  2.,  4.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  4.,  4.,  2.,  2.,  2.,  4.,  2.,
        4.,  4.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,
        4.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,
        2.,  2.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  4.,
        4.,  2.,  2.,  2.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,
        2.,  4.,  2.,  4.,  2.,  4.,  4.,  4.,  2.,  2.,  2.,  4.,  2.,
        2.,  4.,  4.,  2.,  2.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,
        2.,  2.,  4.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2